HR_Project.UI/Areas/Employee/Controllers/EmployeeHomeController.cs
using AutoMapper;
using HR_Project.Entities.Entities;
using HR_Project.Entities.Enums;
using HR_Project.Services.Abstract;
using HR_Project.UI.Areas.Admin.Models;
using HR_Project.UI.Models.DTOs;
using IK.Ui.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Hosting;
using Newtonsoft.Json;
using System;
using System.Net.Http;
using System.Security.Policy;
using System.Text;

namespace HR_Project.UI.Areas.Employee.Controllers
{
    [Area("Employee")]
    [Authorize(Roles = "Employee")]
    public class EmployeeHomeController : Controller
    {
        string baseURL = "https://localhost:7253";
        private readonly IWebHostEnvironment _environment;
        private readonly IGenericService<User> service;
        private readonly IMapper mapper;

        public EmployeeHomeController(IWebHostEnvironment environment, IGenericService<User> service, IMapper mapper)
        {
            _environment = environment;
            this.service = service;
            this.mapper = mapper;
        }
        

        public async Task<IActionResult> Index()
        {
            //var userClaimList = HttpContext.User.Claims.ToList();
            User user = new User();
            using (var httpClient = new HttpClient())
            {
                using (var answ = await httpClient.GetAsync($"{baseURL}/api/User/GetUserByIdInclude/{HttpContext.User.FindFirst("ID").Value}"))
                {
                    string apiResult = await answ.Content.ReadAsStringAsync();
                    user = JsonConvert.DeserializeObject<List<User>>(apiResult)[0];
                }
            }
            return View(user);
        }

        public async Task<IActionResult> SummaryInformation()
        {
            User user = new User();
            List<User> users = new List<User>();
            HashSet<int> departments = new HashSet<int>();
            HashSet<int> jobs = new HashSet<int>();
           
            HashSet<int> advancesPending = new HashSet<int>();
            HashSet<int> advancesCenceled = new HashSet<int>();
            HashSet<int> advancesConfirmed = new HashSet<int>();
            using (var httpClient = new HttpClient())
            {
                using (var answ = await httpClient.GetAsync($"{baseURL}/api/User/GetUserByIdInclude/{HttpContext.User.FindFirst("ID").Value}"))
                {
                    string apiResult = await answ.Content.ReadAsStringAsync();
                    user = JsonConvert.DeserializeObject<List<User>>(apiResult)[0];
                }
                using (var answ = await httpClient.GetAsync($"{baseURL}/api/User/GetAllUserInclude"))
                {
                    string apiResult = await answ.Content.ReadAsStringAsync();
                    users = JsonConvert.DeserializeObject<List<User>>(apiResult);
                }
            }
            foreach (var item in users)
            {
                if (user.DepartmentID != null)
                {
                    departments.Add((int)item.DepartmentID);
                }
                if (user.JobID != null)
                {
                    jobs.Add((int)item.JobID);
                }
                if (item.ID==user.ID)
                {
                    advancesPending.Add(item.Advances.Where(x => x.Status == Status.Pending).ToList().Count());
                    advancesCenceled.Add(item.Advances.Where(x => x.Status == Status.Canceled).ToList().Count());
                    advancesConfirmed.Add(item.Advances.Where(x => x.Status == Status.Confirmed).ToList().Count());

                }
                
            }
            ViewBag.UserCount = users.Count().ToString();
            ViewBag.DepartmentCount = departments.Count().ToString();
            ViewBag.JobCount = jobs.Count().ToString();
            ViewBag.AdvancesCount = advancesPending.Count().ToString();
            ViewBag.AdvancesCenceledCount = advancesCenceled.Count().ToString();
            ViewBag.AdvancesConfirmedCount = advancesConfirmed.Count().ToString();
            return View(user);
        }







        static List<Advance> advances = new List<Advance>();
        public async Task<IActionResult> AdvanceIndex()
        {
            using (var httpClient = new HttpClient())
            {
                using (var cevap = await httpClient.GetAsync($"{baseURL}/api/User/GetAllAdvances/{HttpContext.User.FindFirst("ID").Value}"))
                {
                    string apiCevap = await cevap.Content.ReadAsStringAsync();
                    advances = JsonConvert.DeserializeObject<List<Advance>>(apiCevap);
                }
            }
            if (advances != null)
                return View(advances);
            else
                return View();
        }

        static User updateduser;
        [HttpGet]
        public async Task<IActionResult> UserUpdate(int id)
        {

            List<Department> departments = new List<Department>();
            List<Job> jobs = new List<Job>();

            using (var httpClient = new HttpClient())
            {
                using (var cevap = await httpClient.GetAsync($"{baseURL}/api/User/GetUserById/{id}"))
                {
                    string apiCevap = await cevap.Content.ReadAsStringAsync();
                    updateduser = JsonConvert.DeserializeObject<User>(apiCevap);
                }

                using (var answ = await httpClient.GetAsync($"{baseURL}/api/User/GetAllDepartment"))
                {
                    string apiResult = await answ.Content.ReadAsStringAsync();
                    departments = JsonConvert.DeserializeObject<List<Department>>(apiResult);
                }

                using (var answ = await httpClient.GetAsync($"{baseURL}/api/User/GetAllJob"))
                {
                    string apiResult = await answ.Content.ReadAsStringAsync();
                    jobs = JsonConvert.DeserializeObject<List<Job>>(apiResult);
                }
            }

            ViewBag.GenderList = Enum.GetValues(typeof(Gender))
                         .Cast<Gender>()
                         .Select(g => new SelectListItem
                         {
                             Value = g.ToString(),
                             Text = g.ToString()
                         })
                         .ToList();

            var userDTo = new AddUserDTO()
            {
                JobList = jobs.Select(j => new SelectListItem { Value = j.ID.ToString(), Text = j.JobName }).ToList(),
                DepartmentList = departments.Select(d => new SelectListItem { Value = d.ID.ToString(), Text = d.DepartmentName }).ToList(),
            };
            ViewBag.AddUserDTO = userDTo;
            ViewBag.jobList = jobs;
            ViewBag.departmentList = departments;

            UpdateUserDTO updateUserDTO = mapper.Map<User, UpdateUserDTO>(updateduser);

            return View(updateUserDTO);
        }

        [HttpPost]
        public async Task<IActionResult> UserUpdate(UpdateUserDTO updateUserDTO, List<IFormFile> files)
        {
            if (!ModelState.IsValid)
            {
                return View("UserUpdate");
            }
            string returnedMessaage = Upload.ImageUpload(files, _environment, out bool imgresult);

            //updateduser.FirstName = updateUserDTO.FirstName;
            //updateduser.FirstName2 = updateUserDTO.FirstName2;
            //updateduser.LastName = updateUserDTO.FirstName2;
            //updateduser.BirthPlace = updateUserDTO.BirthPlace;
            //updateduser.PhoneNumber = updateUserDTO.PhoneNumber;
            //updateduser.Photo = returnedMessaage;
            //updateduser. = updateUserDTO.FirstName;

            using (var httpClient = new HttpClient())
            {
                using (var cevap = await httpClient.GetAsync($"{baseURL}/api/User/GetUserByID/{updateUserDTO.ID}"))
                {
                    string apiCevap = await cevap.Content.ReadAsStringAsync();
                    updateduser = JsonConvert.DeserializeObject<User>(apiCevap);

                }
                if (imgresult)
                    updateduser.Photo = returnedMessaage;


                //updateduser = mapper.Map<UpdateUserDTO,User >(updateUserDTO);

                updateduser.FirstName = updateUserDTO.FirstName;
                updateduser.FirstName2 = updateUserDTO.FirstName2;
                updateduser.LastName = updateUserDTO.LastName;
                updateduser.LastName2 = updateUserDTO.LastName2;
                updateduser.Address = updateUserDTO.Address;
                updateduser.BirthPlace = updateUserDTO.BirthPlace;
                updateduser.PhoneNumber = updateUserDTO.PhoneNumber;
                updateduser.Birthdate = updateUserDTO.Birthdate;
                updateduser.StartDateOfWork = updateUserDTO.StartDateOfWork;
                updateduser.Salary = updateUserDTO.Salary;
                updateduser.TCIdentificationNumber = updateUserDTO.TCIdentificationNumber;
                updateduser.JobID = updateUserDTO.JobID;
                updateduser.DepartmentID = updateUserDTO.DepartmentID;


                StringContent content = new StringContent(JsonConvert.SerializeObject(updateduser), Encoding.UTF8, "application/json");

                using (var cevap = await httpClient.PutAsync($"{baseURL}/api/User/UpdateUser/{updateduser.ID}", content))
                {
                    string apiCevap = await cevap.Content.ReadAsStringAsync();
                }
            }

            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> AdvanceApprove()
        {

            using (var httpClient = new HttpClient())
            {
                using (var cevap = await httpClient.GetAsync($"{baseURL}/api/User/ApproveAdvance/{HttpContext.User.FindFirst("ID").Value}"))
                {

HR_Project.UI/Areas/Employee/Views/Shared/_Layoutt.cshtml
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Personal Bootstrap Template</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="~/assets/img/favicon.png" rel="icon">
    <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="~/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="~/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Template Main CSS File -->
    <link href="~/assets/css/style2.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,100,300,700" rel="stylesheet" type="text/css">


    <link rel="stylesheet" href="css/style.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- CSS -->
    <!-- JavaScript -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- =======================================================
    * Template Name: Personal
    * Updated: Jun 18 2023 with Bootstrap v5.3.0
    * Template URL: https://bootstrapmade.com/personal-free-resume-bootstrap-template/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
</head>
<style>

    .photoSize {
        height: 300px;
        width: 300px;
        border-radius: 50%;
    }

    .header-top .photoSize {
        display: none;
    }
</style>
<body>

    <!-- ======= Header ======= -->
    <header id="header" class="header">
        <div class="container">
            <img src="@Context.User.FindFirst("Photo")?.Value" class="photoSize img-fluid" alt="">
            <br />
            <br />
            <br />
            <h1><a style="text-decoration:none;" asp-area="Employee" asp-action="Index" asp-controller="EmployeeHome">@Context.User.FindFirst("FirstName")?.Value @Context.User.FindFirst("Firstname2")?.Value @Context.User.FindFirst("Lastname")?.Value @Context.User.FindFirst("Lastname2")?.Value</a></h1>
            <!-- Uncomment below if you prefer to use an image logo -->
            <!-- <a href="index.html" class="mr-auto"><img src="assets/img/logo.png" alt="" class="img-fluid"></a> -->
            <h2><span>@Context.User.FindFirst("Job")?.Value</span> / <span>@Context.User.FindFirst("Department")?.Value Department</span></h2>

            <nav id="navbar" class="navbar">
                <ul>

                    <li><a class="nav-link" asp-area="Employee" asp-action="Index" asp-controller="EmployeeHome">Home</a></li>
                    <li><a class="nav-link" asp-area="Employee" asp-action="SummaryInformation" asp-controller="EmployeeHome">Summary Information</a></li>
                    <li><a class="nav-link" asp-area="Employee" asp-action="AdvanceIndex" asp-controller="EmployeeHome">Advances</a></li> 
                    <li><a class="nav-link" asp-area="" asp-action="Logout" asp-controller="Home">Log Out</a></li>

                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav><!-- .navbar -->

            <div class="social-links">
                <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
                <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
                <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
                <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
            </div>

        </div>
    </header><!-- End Header -->                                         <!--HOME EKRANI            -->
    @RenderBody()

    <script src="~/assets/vendor/purecounter/purecounter_vanilla.js"></script>
    <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="~/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="~/assets/vendor/swiper/swiper-bundle.min.js"></script>
    <script src="~/assets/vendor/waypoints/noframework.waypoints.js"></script>
    <script src="~/assets/vendor/php-email-form/validate.js"></script>
    <script src="~/assets/js/main2.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>


</body>

HR_Project.UI/Areas/Employee/Views/Shared/_Layouttt.cshtml
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Personal Bootstrap Template</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="~/assets/img/favicon.png" rel="icon">
    <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="~/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="~/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Template Main CSS File -->
    <link href="~/assets/css/style2.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,100,300,700" rel="stylesheet" type="text/css">


    <link rel="stylesheet" href="css/style.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- CSS -->
    <!-- JavaScript -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- =======================================================
    * Template Name: Personal
    * Updated: Jun 18 2023 with Bootstrap v5.3.0
    * Template URL: https://bootstrapmade.com/personal-free-resume-bootstrap-template/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
</head>
<style>

    .photoSize {
        height: 300px;
        width: 300px;
        border-radius: 50%;
    }

    .header-top .photoSize {
        display: none;
    }
</style>
<body>

    <!-- ======= Header ======= -->
    <header id="header" class="header-top">
        <div class="container">
            <img src="@Context.User.FindFirst("Photo")?.Value" class="photoSize img-fluid" alt="">
            <br />
            <br />
            <br />
            <h1><a style="text-decoration:none;" asp-area="Employee" asp-action="Index" asp-controller="EmployeeHome">@Context.User.FindFirst("FirstName")?.Value @Context.User.FindFirst("Firstname2")?.Value @Context.User.FindFirst("Lastname")?.Value @Context.User.FindFirst("Lastname2")?.Value</a></h1>
            <!-- Uncomment below if you prefer to use an image logo -->
            <!-- <a href="index.html" class="mr-auto"><img src="assets/img/logo.png" alt="" class="img-fluid"></a> -->
            <h2><span>@Context.User.FindFirst("Job")?.Value</span> / <span>@Context.User.FindFirst("Department")?.Value Department</span></h2>

            <nav id="navbar" class="navbar">
                <ul>

                    <li><a class="nav-link" asp-area="Employee" asp-action="Index" asp-controller="EmployeeHome">Home</a></li>
                    <li><a class="nav-link" asp-area="Employee" asp-action="SummaryInformation" asp-controller="EmployeeHome">Summary Information</a></li>
                    <li><a class="nav-link" asp-area="Employee" asp-action="AdvanceIndex" asp-controller="EmployeeHome">Advances</a></li>
                    <li><a class="nav-link" asp-area="" asp-action="Logout" asp-controller="Home">Log Out</a></li>

                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav><!-- .navbar -->

            <div class="social-links">
                <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
                <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
                <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
                <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
            </div>

        </div>
    </header><!-- End Header -->                                         <!--HOME EKRANI            -->
    @RenderBody()

    <script src="~/assets/vendor/purecounter/purecounter_vanilla.js"></script>
    <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="~/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="~/assets/vendor/swiper/swiper-bundle.min.js"></script>
    <script src="~/assets/vendor/waypoints/noframework.waypoints.js"></script>
    <script src="~/assets/vendor/php-email-form/validate.js"></script>
    <script src="~/assets/js/main2.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>


</body>