HR_Project.UI/Areas/Admin/Controllers/AdminHomeController.cs
using AutoMapper;
using HR_Project.Entities.Entities;
using HR_Project.Entities.Enums;
using HR_Project.Services.Abstract;
using HR_Project.UI.Areas.Admin.Models;
using HR_Project.UI.Areas.CompanyManager.Models;
using HR_Project.UI.Models;
using HR_Project.UI.Models.DTOs;
using IK.Ui.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System.ComponentModel.Design;
using System.Security.Cryptography;
using System.Text;

namespace HR_Project.UI.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class AdminHomeController : Controller
    {
        public AdminHomeController(IWebHostEnvironment environment, IGenericService<User> service, IMapper mapper)
        {
            this.environment = environment;
            this.service = service;
            this.mapper = mapper;
        }
        string baseURL = "https://localhost:7253";
        private readonly IWebHostEnvironment environment;
        private readonly IGenericService<User> service;
        private readonly IMapper mapper;

        public async Task<IActionResult> Index()
        {
            //var userClaimList = HttpContext.User.Claims.ToList();
            User user = new User();
            using (var httpClient = new HttpClient())
            {
                using (var answ = await httpClient.GetAsync($"{baseURL}/api/User/GetUserByIdInclude/{HttpContext.User.FindFirst("ID").Value}"))
                {
                    string apiResult = await answ.Content.ReadAsStringAsync();
                    user = JsonConvert.DeserializeObject<List<User>>(apiResult)[0];
                }
            }
            return View(user);
        }

        public async Task<IActionResult> SummaryInformation()
        {
            //var userClaimList = HttpContext.User.Claims.ToList();
            User user = new User();
            List<User> users = new List<User>();
            HashSet<int> departments = new HashSet<int>();
            HashSet<int> jobs = new HashSet<int>();
            HashSet<int> advances = new HashSet<int>();
            using (var httpClient = new HttpClient())
            {
                using (var answ = await httpClient.GetAsync($"{baseURL}/api/User/GetUserByIdInclude/{HttpContext.User.FindFirst("ID").Value}"))
                {
                    string apiResult = await answ.Content.ReadAsStringAsync();
                    user = JsonConvert.DeserializeObject<List<User>>(apiResult)[0];
                }
                using (var answ = await httpClient.GetAsync($"{baseURL}/api/User/GetAllUserInclude"))
                {
                    string apiResult = await answ.Content.ReadAsStringAsync();
                    users = JsonConvert.DeserializeObject<List<User>>(apiResult);
                }
            }
            foreach (var item in users)
            {
                if (user.DepartmentID != null)
                {
                    departments.Add((int)item.DepartmentID);
                }
                if (user.JobID != null)
                {
                    jobs.Add((int)item.JobID);
                }
                advances.Add(item.Advances.Where(x => x.Status == Status.Pending).ToList().Count());
            }
            ViewBag.UserCount = users.Count().ToString();
            ViewBag.DepartmentCount = departments.Count().ToString();
            ViewBag.JobCount = jobs.Count().ToString();
            ViewBag.AdvancesCount = advances.Count().ToString();
            return View(user);
        }

        public async Task<IActionResult> ListCompany()
        {
            List<Company> companies = new List<Company>();

            using (var httpClient = new HttpClient())
            {
                using (var result = await httpClient.GetAsync($"{baseURL}/api/Company/GetAllCompanies"))
                {
                    string apiResult = await result.Content.ReadAsStringAsync();
                    companies = JsonConvert.DeserializeObject<List<Company>>(apiResult);
                }
            }
            var companiess = companies.Where(x => x.IsActive == true).ToList();

            return View(companiess);
        }

        Dictionary<CompanyTitle, string> enumDisplayNames = new Dictionary<CompanyTitle, string>
        {
            { CompanyTitle.AnonimSirket, "Anonim Şirket" },
            { CompanyTitle.LimitedSirket, "Limited Şirket" }
        };

        [HttpGet]
        public async Task<IActionResult> AddCompany()
        {
            ViewBag.TitleList = Enum.GetValues(typeof(CompanyTitle))
             .Cast<CompanyTitle>()
             .Select(g => new SelectListItem
             {
                 Value = g.ToString(),
                 Text = enumDisplayNames.ContainsKey(g) ? enumDisplayNames[g] : g.ToString()
             })
             .ToList();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddCompany(Company company, List<IFormFile> files)
        {
            string returnedMessaage = Upload.ImageUpload(files, environment, out bool imgresult);

            if (!ModelState.IsValid || (imgresult == false && returnedMessaage != "Dosya seçilmedi"))
            {
                ViewBag.TitleList = Enum.GetValues(typeof(CompanyTitle))
             .Cast<CompanyTitle>()
             .Select(g => new SelectListItem
             {
                 Value = g.ToString(),
                 Text = enumDisplayNames.ContainsKey(g) ? enumDisplayNames[g] : g.ToString()
             })
             .ToList();
                return View("AddCompany");
            }

            company.IsActive = true;
            if (imgresult)
            {
                company.Logo = returnedMessaage;
                using (var httpClient = new HttpClient())
                {
                    StringContent content = new StringContent(JsonConvert.SerializeObject(company), Encoding.UTF8, "application/json");
                    using (var answ = await httpClient.PostAsync($"{baseURL}/api/Company/CreateCompany", content))
                    {
                        string apiResult = await answ.Content.ReadAsStringAsync();
                    }
                }
            }
            return RedirectToAction("ListCompany");
        }

        static List<Department> departments;
        static List<Job> jobs;
        static List<Company> companies;
        static User updateduser;
        [HttpGet]
        public async Task<IActionResult> UserUpdate(int id)
        {

            departments = new List<Department>();
            jobs = new List<Job>();

            using (var httpClient = new HttpClient())
            {
                using (var cevap = await httpClient.GetAsync($"{baseURL}/api/User/GetUserById/{id}"))
                {
                    string apiCevap = await cevap.Content.ReadAsStringAsync();
                    updateduser = JsonConvert.DeserializeObject<User>(apiCevap);
                }

                using (var answ = await httpClient.GetAsync($"{baseURL}/api/User/GetAllDepartment"))
                {
                    string apiResult = await answ.Content.ReadAsStringAsync();
                    departments = JsonConvert.DeserializeObject<List<Department>>(apiResult);
                }

                using (var answ = await httpClient.GetAsync($"{baseURL}/api/User/GetAllJob"))
                {
                    string apiResult = await answ.Content.ReadAsStringAsync();
                    jobs = JsonConvert.DeserializeObject<List<Job>>(apiResult);
                }
                using (var answ = await httpClient.GetAsync($"{baseURL}/api/User/GetAllCompanies"))
                {
                    string apiResult = await answ.Content.ReadAsStringAsync();
                    companies = JsonConvert.DeserializeObject<List<Company>>(apiResult);
                }
            }

            ViewBag.GenderList = Enum.GetValues(typeof(Gender))
                         .Cast<Gender>()
                         .Select(g => new SelectListItem
                         {
                             Value = g.ToString(),
                             Text = g.ToString()
                         })
                         .ToList();

            var userDTo = new AddUserDTO()
            {
                JobList = jobs.Select(j => new SelectListItem { Value = j.ID.ToString(), Text = j.JobName }).ToList(),
                DepartmentList = departments.Select(d => new SelectListItem { Value = d.ID.ToString(), Text = d.DepartmentName }).ToList(),
            };
            ViewBag.AddUserDTO = userDTo;
            ViewBag.jobList = jobs;
            ViewBag.departmentList = departments;
            ViewBag.companyList = companies;

            UpdateUserDTO updateUserDTO = mapper.Map<User, UpdateUserDTO>(updateduser);

            return View(updateUserDTO);
        }

        [HttpPost]
        public async Task<IActionResult> UserUpdate(UpdateUserDTO updateUserDTO, List<IFormFile> files)
        {
            if (!ModelState.IsValid)
            {
                return View("UserUpdate");
            }
            string returnedMessaage = Upload.ImageUpload(files, environment, out bool imgresult);

            using (var httpClient = new HttpClient())
            {
                using (var cevap = await httpClient.GetAsync($"{baseURL}/api/User/GetUserByID/{updateUserDTO.ID}"))
                {
                    string apiCevap = await cevap.Content.ReadAsStringAsync();
                    updateduser = JsonConvert.DeserializeObject<User>(apiCevap);

                }
                if (imgresult)
                    updateduser.Photo = returnedMessaage;


                //updateduser = mapper.Map<UpdateUserDTO,User >(updateUserDTO);

                updateduser.FirstName = updateUserDTO.FirstName;
                updateduser.FirstName2 = updateUserDTO.FirstName2;

HR_Project.UI/Areas/Admin/Views/AdminHome/AddCompany.cshtml
@using HR_Project.Entities.Entities;
@model Company

@{
    ViewData["Title"] = "AddCompany";
    Layout = "~/Areas/Admin/Views/Shared/_Layouttt.cshtml";
    var titleList = ViewBag.TitleList as List<CompanyTitle>;
}
<style>
    .table img {
        max-width: 50px; /* Maksimum genişlik */
        max-height: 50px; /* Maksimum yükseklik */
        object-fit: cover; /* Orantılı olarak fotoğrafı sığdır */
        border-radius: 50%; /* Yuvarlak kenarlıklar */
    }

    span {
        color: white;
    }

    th {
        font-size: 16px;
        font-weight: bold;
    }

    td {
        font-size: 13px;
    }

    .pclass {
        margin-top: 30px;
    }

    label {
        color: white;
    }

    .selectDesign {
        padding: 10px 15px;
        background-color: #FFFFFF14;
    }

    .normalTd {
        margin-top: -5px;
    }

    .optionColor > option {
        background-color: #FFFFFF14;
        color: black;
    }

    .formDesign {
        padding: 30px;
        background: rgba(255, 255, 255, 0.08);
        margin: 0;
        font-family: var(--bs-body-font-family);
        font-size: var(--bs-body-font-size);
        font-weight: var(--bs-body-font-weight);
        line-height: var(--bs-body-line-height);
        color: var(--bs-body-color);
        text-align: var(--bs-body-text-align);
        background-color: rgba(255, 255, 255, 0.08);
        -webkit-text-size-adjust: 100%;
        -webkit-tap-highlight-color: transparent;
    }

    .form-group select {
        background-color: rgba(255, 255, 255, 0.08);
        border: hidden;
        border-block-color: rgba(255, 255, 255, 0.08);
        color: white;
    }

        .form-group select:focus {
            background-color: rgba(255, 255, 255, 0.08) !important;
            color: white;
        }

    .form-group input {
        background-color: rgba(255, 255, 255, 0.08);
        border: hidden;
        border-block-color: rgba(255, 255, 255, 0.08);
        color: white;
    }

        .form-group input:focus {
            background-color: rgba(255, 255, 255, 0.08) !important;
            color: white;
        }

    .pagination {
        display: flex;
        justify-content: center;
        list-style-type: none;
        margin: 0;
        padding: 0;
    }

        .pagination li {
            margin: 0 5px;
        }

            .pagination li a {
                color: black;
                text-decoration: none;
                padding: 5px 10px;
                border: 1px solid #ccc;
                border-radius: 3px;
            }

                .pagination li a.active {
                    background-color: #ccc;
                }

                .pagination li a:hover {
                    background-color: #f5f5f5;
                }
</style>
<head>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="	https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" rel="stylesheet" />

</head>

<section id="contact" class="contact section-show">
    <div class="container">
        <div class="section-title">
            <h2>Registration</h2>
        </div>
        <form asp-action="AddCompany" asp-area="Admin" asp-controller="AdminHome" enctype="multipart/form-data" method="post" class="formDesign mt-4">
            <div class="form-group mt-3">
                <div class="row">
                    <div class="col-md-6 form-group">
                        <label asp-for="CompanyName">Company Name</label>
                        <input asp-for="CompanyName" type="text" class="form-control" placeholder="Company Name" required="">
                        <span asp-validation-for="CompanyName" class="text-danger"></span>
                    </div>
                    <div class="col-md-6 form-group mt-3 mt-md-0">
                        <label asp-for="MersisNo">Mersis No</label>
                        <input asp-for="MersisNo" type="text" class="form-control" placeholder="Mersis No" required="">
                        <span asp-validation-for="MersisNo" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="form-group mt-3">
                <div class="row">
                    <div class="col-md-6 form-group">
                        <label asp-for="TaxNumber">Tax Number</label>
                        <input asp-for="TaxNumber" type="text" class="form-control" placeholder="Tax Number">
                        <span asp-validation-for="TaxNumber" class="text-danger"></span>

                    </div>
                    <div class="col-md-6 form-group mt-3 mt-md-0">
                        <label asp-for="TaxOffice">Tax Office</label>
                        <input asp-for="TaxOffice" type="text" class="form-control" placeholder="Tax Office">
                        <span asp-validation-for="TaxOffice" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="form-group mt-3">
                <div class="row">
                    <div class="col-md-6 form-group">
                        <label asp-for="YearOfFoundation">Date Of Foundation</label>
                        <input asp-for="YearOfFoundation" class="dateInput form-control form-control-md" type="date" data-date="" data-date-format="DD MMMM YYYY">
                        <span asp-validation-for="YearOfFoundation" class="text-danger"></span>
                    </div>
                    <div class="col-md-6 form-group mt-3 mt-md-0">
                        <label asp-for="NumberOfEmployees">Number Of Employees</label>
                        <input asp-for="NumberOfEmployees" class="form-control form-control-md" />
                        <span asp-validation-for="NumberOfEmployees" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="form-group mt-3">
                <label asp-for="CompanyTitle">Company Title</label>
                <select style="background-color:#FFFFFF14; color:white" class="optionColor form-select form-select-md" aria-label="Default select example" asp-for="CompanyTitle">
                    @foreach (var item in ViewBag.TitleList)
                    {
                        <option value="@item.Value">@item.Text</option>
                    }
                </select>
                <span asp-validation-for="CompanyTitle" class="text-danger"></span>
            </div>
            <div class="form-group mt-3">
                <label asp-for="Email">Email</label>
                <input asp-for="Email" type="email" class="form-control" placeholder="Email">
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group mt-3">
                <div class="row">
                    <div class="col-md-6 form-group">
                        <label asp-for="ContractStartDate">Start Date Of Contract</label>
                        <input asp-for="ContractStartDate" class="dateInput form-control form-control-md" type="date" data-date="" data-date-format="DD MMMM YYYY">
                        <span asp-validation-for="ContractStartDate" class="text-danger"></span>
                    </div>
                    <div class="col-md-6 form-group mt-3 mt-md-0">
                        <label asp-for="ContractFinishDate">End Date Of Contract</label>
                        <input asp-for="ContractFinishDate" class="dateInput form-control form-control-md" type="date" data-date="" data-date-format="DD MMMM YYYY">
                        <span asp-validation-for="ContractFinishDate" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="form-group mt-3">
                <div class="row">
                    <div class="col-md-6 form-group">
                        <label asp-for="PhoneNumber">Phone</label>
                        <input type="text" class="form-control form-control-md" asp-for="PhoneNumber" maxlength="10" placeholder="(Please write after +90)" />
                        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                    </div>
                    <div class="col-md-6 form-group mt-3 mt-md-0">
                        <label asp-for="Address"></label>
                        <input asp-for="Address" class="form-control" placeholder="Address" />
                        <span asp-validation-for="Address" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="form-group mt-3">
                <div class="row">
                    <div class="col-md-6 form-group">
                        <label asp-for="Logo">Choose Company Logo</label>
                        <input asp-for="Logo" name="files" type="file" id="image-upload" accept=".png, .jpg, .jpeg" class="form-control form-control-md" />
                    </div>
                </div>
            </div>
            <div class="my-3">
                
            </div>
            <div style="margin-left:1000px;" class="text-center">< <input class="btn btn-success" type="submit" value="Register Company" onclick="submitForm()"></></div>
        </form>
    </div>
</section><!-- End Contact Section -->                  <!--CONTACT EKRANI            -->

<script>
    function submitForm() {
        var form = document.getElementById('updateUserForm');

        var fileInput = document.getElementById('image-upload');
        var file = fileInput.files[0];
        var fileSize = file.size;
        var maxSizeInBytes = 4 * 1024 * 1024; // Maksimum 4MB (4 * 1024 * 1024 byte)
        if (fileSize > maxSizeInBytes) {
            alert("Dosya boyutu çok büyük! Lütfen maksimum 4MB boyutunda bir dosya seçin.");
            return;
        }

        var fileExtension = file.name.split('.').pop().toLowerCase();
        if (fileExtension !== 'png' && fileExtension !== 'jpg' && fileExtension !== 'jpeg') {
            alert("Geçersiz dosya uzantısı! Sadece .png, .jpg veya .jpeg uzantılı dosyaları seçin.");
            return;
        }

        // FormData nesnesini oluşturarak form verilerini alın
        var formData = new FormData(form);
        // Dosyayı formData'ya ekleyin
        formData.append('files', file);

        // FormData'yı doğru bir şekilde göndermek için XMLHttpRequest kullanın
        var xhr = new XMLHttpRequest();
        xhr.open('POST', form.action);
        xhr.onload = function () {
            if (xhr.status === 200) {
                alert("Güncelleme işlemi başarıyla tamamlandı!");
                window.location.href = '/CompanyManager/CompanyManagerHome/AddUser'; // Index sayfasına yönlendirme
            } else {
                alert("Güncelleme işlemi sırasında bir hata oluştu.");
            }
        };
        // Content-Type başlığını ayarlamaya gerek yok, otomatik olarak ayarlanır.
        xhr.send(formData);
    }
</script>

HR_Project.UI/Areas/Admin/Views/AdminHome/SummaryInformation.cshtml
<html lang="en">
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layouttt.cshtml";
    var jobList = ViewBag.jobList as List<Job>;
    var departmentList = ViewBag.departmentList as List<Department>;
}
@model User
<head>
    @*<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">*@

    <!-- JavaScript -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<style>
    /* Modal Background */
    .modal-overlay {
        display: none;
        position: fixed;
        top: 0;
        left: 0;
        z-index: 1050;
        width: 100%;
        height: 100%;
        background-color: rgba(0, 0, 0, 0.5);
    }

    /* Modal Container */
    .modal-container {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        background-color: #212529;
        color: white;
        padding: 20px;
        border-radius: 5px;
    }

    /* Modal Close Button */
    .modal-close {
        position: absolute;
        top: 10px;
        right: 10px;
        color: white;
        cursor: pointer;
    }
</style>


<style>
    strong {
        color: cadetblue;
    }

    span {
        color: white;
        font-weight: bold;
    }

    .count-box p {
        color: white;
    }
</style>
<style>
    .modalHeight {
        height: 34px;
    }



    .difcol {
        color: darkblue;
        font-weight: bold;
    }

    .col-sm-9 p {
        margin-left: 100px;
    }

    .col-sm-3 p {
        margin-left: -100px;
    }

    .spec {
        display: flex;
        justify-content: space-between
    }


    .les {
        height: 15px;
    }
</style>
<!-- ======= About Section ======= -->
<section id="about" class="about section-show">

    <!-- ======= About Me ======= -->
    <div class="about-me container">
        <div class="section-title">
            <h2>Summary Information</h2>
        </div>
        <div class="row">
            <div class="col-lg-4" data-aos="fade-right">
                <img src="@Model.Photo" class="img-fluid" alt="">
            </div>
            <div class="col-lg-8 pt-4 pt-lg-0 content" data-aos="fade-left">
                <h3>Company Manager</h3>
                <br />
                <div class="row">
                    <div class="col-lg-6">
                        <ul>
                            <li>
                                <i class="bi bi-chevron-right"></i> <strong>First Name :</strong> <span>@Model.FirstName</span>
                            </li>
                            <li>
                                <i class="bi bi-chevron-right"></i> <strong>Middle Name : </strong> <span>@Model.FirstName2</span>
                            </li>
                            <li>
                                <i class="bi bi-chevron-right"></i> <strong>Email :</strong> <span>@Model.Email</span>
                            </li>
                            <li>
                                <i class="bi bi-chevron-right"></i> <strong>Adress :</strong> <span>@Model.Address / @Model.City</span>
                            </li>

                        </ul>
                    </div>
                    <div class="col-lg-6">
                        <ul>
                            <li><i class="bi bi-chevron-right"></i> <strong>Last Name :</strong> <span>@Model.LastName</span></li>
                            <li><i class="bi bi-chevron-right"></i> <strong>Maiden Name :</strong> <span>@Model.LastName2</span></li>
                            <li><i class="bi bi-chevron-right"></i> <strong>Phone :</strong> <span>@string.Format("{0:0(###) ###-####}", double.Parse(Model.PhoneNumber))</span></li>
                            <li>
                                <i class="bi bi-chevron-right"></i> 
                                <button data-toggle="modal" data-target="#detailModal" type="button" class="btn btn-warning">Details</button> &nbsp;<a asp-area="Admin" asp-controller="AdminHome" asp-action="UpdateUserToSummaryInformation" asp-route-id="@Model.ID" type="button" class="btn btn-primary ms-4">Update</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div><!-- End About Me -->
    <!-- ======= Counts ======= -->
    <div class="counts container">
        <div class="row">
            <div class="col-lg-3 col-md-6">
                <div class="count-box">
                    <i class="bi bi-emoji-smile"></i>
                    <span>@ViewBag.UserCount</span>
                    <p>Users</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 mt-5 mt-md-0">
                <div class="count-box">
                    <i class="bi bi-journal-richtext"></i>
                    <span>@ViewBag.DepartmentCount</span>
                    <p>Departments</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 mt-5 mt-lg-0">
                <div class="count-box">
                    <i class="bi bi-headset"></i>
                    <span>@ViewBag.JobCount</span>
                    <p>Jobs</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 mt-5 mt-lg-0">
                <div class="count-box">
                    <i class="bi bi-award"></i>
                    <span>@ViewBag.AdvancesCount</span>
                    <p>Pending Advances</p>
                </div>
            </div>
        </div>
    </div><!-- End Counts -->
</section>



<div class="modal" tabindex="-1" role="dialog" id="detailModal">
    <div class="modal-dialog modal-lg">
        <div style="background-color:#212529" class="modal-content">
            <div style="background-color:#212529" class="modal-body">
                <div style="flex; align-items:center; margin-left:308.5px;">
                    <img src="@Model.Photo" alt="avatar" class="rounded-circle img-fluid" style="width: 150px;">
                </div>
                <div style="background-color:#212529; margin-top:30px;" class="card mb-4">
                    <table style="border:hidden;" class="table table-dark">
                        <thead>
                            <tr>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>First Name :</td>
                                <td><p>@Model.FirstName</p></td>
                            </tr>
                            <tr>
                                <td>Middle Name :</td>
                                <td><p>@Model.FirstName2</p></td>
                            </tr>
                            <tr>
                                <td>Last Name :</td>
                                <td><p>@Model.LastName</p></td>
                            </tr>
                            <tr>
                                <td>Maiden Name :</td>
                                <td><p>@Model.LastName2</p></td>
                            </tr>
                            <tr>
                                <td>Birth Date :</td>
                                <td><p type="date" data-date="" data-date-format="DD MMMM YYYY">@Model.FormattedBirthdate</p></td>
                            </tr>
                            <tr>
                                <td>Birth Place :</td>
                                <td><p>@Model.BirthPlace</p></td>
                            </tr>
                            <tr>
                                <td>Email :</td>
                                <td><p>@Model.Email</p></td>
                            </tr>
                            <tr>
                                <td>Phone :</td>
                                <td><p>@string.Format("{0:0(###) ###-####}", double.Parse(Model.PhoneNumber))</p></td>
                            </tr>
                            <tr>
                                <td>Address :</td>
                                <td><p>@Model.Address</p></td>
                            </tr>
                            <tr>
                                <td>Job :</td>
                                <td><p>@Model.Job.JobName</p></td>
                            </tr>
                            <tr>
                                <td>Company Name :</td>
                                <td><p>@Model.Company.CompanyName</p></td>
                            </tr>
                            <tr>
                                <td>Department :</td>
                                <td><p>@Model.Department.DepartmentName</p></td>
                            </tr>
                            <tr>
                                <td>Start Date Of Work :</td>
                                <td><p style="color:white" type="text" data-date="" data-date-format="DD MMMM YYYY">@Model.StartDateOfWork.ToShortDateString()</p></td>
                            </tr>
                            <tr>
                                <td>Dismissal Date :</td>
                                <td><p style="color:white" type="text" data-date="" data-date-format="DD MMMM YYYY">@Model.FormattedDismissalDate</p></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>
<!-- /.modal --

<!-- Vendor JS Files -->
<script src="~/assets/vendor/purecounter/purecounter_vanilla.js"></script>
<script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="~/assets/vendor/glightbox/js/glightbox.min.js"></script>
<script src="~/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
<script src="~/assets/vendor/swiper/swiper-bundle.min.js"></script>
<script src="~/assets/vendor/waypoints/noframework.waypoints.js"></script>
<script src="~/assets/vendor/php-email-form/validate.js"></script>

<!-- Template Main JS File -->
<script src="~/assets/js/main2.js"></script>

<script>
    function openModal() {
        var modalOverlay = document.getElementById("modalOverlay");
        modalOverlay.style.display = "block";
    }

    function closeModal() {
        var modalOverlay = document.getElementById("modalOverlay");
        modalOverlay.style.display = "none";
    }
</script>

</html>